put more stuff to stderr

diff --git a/bash/boxify b/bash/boxify
--- a/bash/boxify
+++ b/bash/boxify
@@ -13,6 +13,7 @@ usage() {
   color_names=${color_names%, }
 
   # help message
+  local me
   me=$(basename -- "$0")
   cat << HEREDOC
 usage: $me -l <pad> -r <pad> -c <clr> -b <clr>
@@ -62,11 +63,11 @@ get_args() {
       -r) rpadding="$2"; shift; shift ;;
       -c) text_color="$2"; shift; shift ;;
       -b) line_color="$2"; shift; shift ;;
-      *) echo "unknown option '$1'"; usage; exit 1 ;;
+      *) echo "unknown option '$1'" >&2; usage >&2; exit 1 ;;
     esac
   done
   if [[ ! ("$lpadding" =~ ^[0-9]+$ && "$rpadding" =~ ^[0-9]+$) ]]; then
-    echo "error: padding must be a positive integer"
+    echo "error: padding must be a positive integer" >&2
     exit 1
   fi
   return 0
diff --git a/bash/etcher b/bash/etcher
--- a/bash/etcher
+++ b/bash/etcher
@@ -7,9 +7,8 @@
 #
 
 usage() {
-  me=$(basename -- "$0")
   cat << HEREDOC
-usage: $me <image> [-d <dev>]
+usage: $(basename -- "$0") <image> [-d <dev>]
 
 required args:
   <image>  path to the disk image to write
@@ -40,13 +39,13 @@ get_args() {
     case $1 in
       -h|--help) usage; exit 0 ;;
       -d) device="$2"; shift; shift ;;
-      -*) echo "unknown option '$1'"; usage; exit 1 ;;
+      -*) echo "unknown option '$1'" >&2; usage >&2; exit 1 ;;
       *) positional+=("$1"); shift ;;
     esac
   done
   image="${positional[0]}"
   if [[ -z "$image" ]]; then
-    echo "missing required argument <image>"; usage; exit 1
+    echo "missing required argument <image>" >&2; usage >&2; exit 1
   fi
   return 0
 }
@@ -78,10 +77,12 @@ get_args "$@"
 
 # confirm that image exists
 if [[ ! -r "$image" ]]; then
-  echo "${RED}error${RST}: cannot read '$image'"; exit 1
+  echo "${RED}error${RST}: cannot read '$image'" >&2
+  exit 1
 fi
 if ! file -b --mime-type "$image" | grep -q 'iso'; then
-  echo "${RED}error${RST}: invalid disk image '$image'"; exit 1
+  echo "${RED}error${RST}: invalid disk image '$image'" >&2
+  exit 1
 fi
 
 set -e
@@ -110,7 +111,7 @@ if [[ "$image" =~ \.iso$ ]]; then
       image="$dmg"
       echo "${GRN}success${RST}: using the dmg from now on"
     else
-      echo "${RED}error${RST}: failed to convert '$image' to '$dmg'"
+      echo "${RED}error${RST}: failed to convert '$image' to '$dmg'" >&2
       exit 1
     fi
   else
@@ -141,7 +142,7 @@ done
 # unmount the device
 echo "unmounting ${MGN}$device${RST}..."
 if ! diskutil unmountDisk "$device"; then
-  echo "${RED}error${RST}: failed to unmount ${MGN}$device${RST}"
+  echo "${RED}error${RST}: failed to unmount ${MGN}$device${RST}" >&2
   exit 1
 fi
 
@@ -162,7 +163,7 @@ fi
 # perform the write
 echo "writing ${CYN}$image${RST} to ${MGN}$device${RST}..."
 if ! sudo dd if="$image" bs=1M of="$device" status=progress; then
-  echo "${RED}error${RST}: failed to write ${CYN}$image${RST} to ${MGN}$device${RST}"
+  echo "${RED}error${RST}: failed to write ${CYN}$image${RST} to ${MGN}$device${RST}" >&2
   exit 1
 fi
 
